[build]
  command = "npm run build"
  publish = "frontend/build"
  functions = "backend/functions"

[dev]
  functions = "backend/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
