[build]
  base = ""
  publish = "build"
  command = "npm run build"

[build.environment]
  NETLIFY_USE_YARN = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify\functions"
