[build]
builder = "nixpacks/python"

[build.dependencies]
# Specify the required Python version and other dependencies
python = "3.9"

[build.commands]
install = "pip install -r requirements.txt"

[build.environment]
FLASK_ENV = "production"

[start]
command = "gunicorn app:app"

[start.environment]
FLASK_ENV = "production"
