[build]
packages = [
  "python38"
]
commands = [
  "python -m venv venv",
  ". venv/bin/activate && pip install -r requirements.txt"
]

[start]
command = ". venv/bin/activate && python app.py"
