[phases.install]
description = "Install dependencies"
command = "pip install -r requirements.txt"

[phases.build]
description = "Build the application"
command = ""

[phases.start]
description = "Start the application"
command = "gunicorn app:app"
